#!/usr/bin/env bash
# script that will display information about subdomains.
print_info ()
{
	dig "$2.$1" | awk '/ANSWER SECTION:/{getline; printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$2"
}

declare -a subdomains=("www" "lb-01" "web-01" "web-02")

for name in "${subdomains[@]}"; do
	if [ "$2"  == "$name" ] || [ -z "$2" ]; then
		print_info "$1" "$name"
	fi
done
