#!/usr/bin/env bash
# script that install nginx
# command for update system
sudo apt-get update
# command for install nginx
sudo apt-get -y install nginx
# commando for start service nginx
sudo /etc/init.d/nginx start
# commando for overwrite index.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
# create new string to add
sudo sed '/server_name _;/a\t rewrite ^/redirect_me https://www.holbertonschool.com/ permanent' /etc/nginx/sites-available/default;
# restart nginx
sudo systemctl restart nginx
