#!/usr/bin/env bash
# script that install nginx
# command for update system
sudo apt-get update
# command for install nginx
sudo apt-get -y install nginx
# commando for start service nginx
sudo /etc/init.d/nginx start
# commando for overwrite index.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
# create new string to add
string="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=hQsZUVMwEls permanent;"
sudo sed -i "s/server_name _;/$string/" /etc/nginx/sites-available/default
# create redirect to 404 page not found
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
error_page="server_name _;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/server_name _;/$error_page/" /etc/nginx/sites-available/default
# restart nginx
sudo service nginx restart
