#!/usr/bin/env bash
# script that configure HTTP response whit custom header
# create new string to add
sudo apt-get  update
sudo apt-get -y install nginx
string="http {\n\tadd_header X-Served-By \"$HOSTNAME\";"
sudo sed -i "s/http {/$string/" /etc/nginx/nginx.conf
# restart nginx
sudo service nginx restart
