#!/usr/bin/env bash
# script for install and configurate HAproxy
sudo apt-get install software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.0 -y
sudo apt-get update
sudo apt-get install haproxy=2.0.\* -y
echo "frontend haproxynode
	bind *:80
	mode http
	default_backend backendnodes

backend backendnodes
	balance roundrobin
	server web1 34.73.226.110:80 check
	server web2 35.243.175.109:80 check
	" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
