#!/usr/bin/env bash
# Script that create file holbertonscript.pid and habdle signals
echo $$ > /var/run/holbertonscript.pid
while :
do
	trap "echo Y U no love me?!; exit" SIGINT
	trap "echo I hate the kill command; rm /var/run/holbertonscript.pid; exit" SIGTERM SIGQUIT
	echo "To infinity and beyond"
	sleep 2
done 
