#!/usr/bin/env bash
# script that manage the file manage_my_process

if [ "$1" == "start" ]; then
	./manage_my_process &
	sudo -S touch /var/run/my_process.pid
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process started"
elif [ "$1" == "stop" ]; then
	kill "$(cat /var/run/my_process.id)"
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"
elif [ "$1" == "restart" ]; then
	kill "$(cat /var/run/my_process.id)"
	rm /var/run/my_process.pid
	touch /var/run/my_process.pid
	echo "$!" > /var/run/my_process.pid
	./manage_my_process &
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"


fi
