#!/usr/bin/env bash
# script that loops from 1 to 10 adn display bad luck in 4 , good luck in 8 

i=1
while [ $i -lt 11 ]; do
	if [ $i = 4 ]; then
		echo "bad luck"
	elif [ $i = 8 ]; then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	let i+=1
done
