#!/usr/bin/env bash
# script that configures the container
chmod 766 /etc/nginx/nginx.conf
pkill -o apache2
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo su "nginx" service nginx restart
